package pl.matsuo.elm.pkg;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * A dependency lockfile ({@code elm.lock}): the exact resolved version of every package in the
 * solution — direct and indirect — each with an integrity hash, so installs are reproducible and
 * tamper-evident. The hash is a SHA-256 over the package's canonical resolution ({@code name@version}
 * plus its sorted dependency constraints, as reported by the {@link Registry}); if a registry later
 * serves a different dependency set for a pinned version, {@link #verify} flags the mismatch.
 *
 * <p>The format is a small line-based text (stable ordering, easy to diff):
 *
 * <pre>
 * # elm.lock — generated by elm-lang; do not edit by hand
 * lockfileVersion 1
 * author/name 1.2.3 sha256-BASE64HASH
 * …
 * </pre>
 */
public final class Lockfile {

  /** The on-disk lockfile name, alongside {@code elm.json}. */
  public static final String FILENAME = "elm.lock";

  private static final int FORMAT_VERSION = 1;

  /** One locked package: its pinned version and integrity hash. */
  public record Entry(Version version, String integrity) {}

  private final SortedMap<String, Entry> packages;

  private Lockfile(SortedMap<String, Entry> packages) {
    this.packages = packages;
  }

  /** The locked packages, keyed by {@code author/name}, in sorted order. */
  public SortedMap<String, Entry> packages() {
    return packages;
  }

  /** Builds a lockfile for a solved dependency set, hashing each package against the registry. */
  public static Lockfile of(Map<String, Version> solution, Registry registry) {
    SortedMap<String, Entry> entries = new TreeMap<>();
    solution.forEach((pkg, version) -> entries.put(pkg, new Entry(version, integrity(pkg, version, registry))));
    return new Lockfile(entries);
  }

  /** The integrity string {@code sha256-<base64>} of a package's canonical resolution. */
  public static String integrity(String pkg, Version version, Registry registry) {
    StringBuilder canonical = new StringBuilder(pkg).append('@').append(version).append('\n');
    // Dependency constraints, sorted by package, so the hash is independent of registry iteration order.
    new TreeMap<>(registry.dependencies(pkg, version))
        .forEach((dep, constraint) -> canonical.append(dep).append(' ').append(constraint).append('\n'));
    return "sha256-" + base64Sha256(canonical.toString());
  }

  private static String base64Sha256(String text) {
    try {
      byte[] digest = MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));
      return Base64.getEncoder().encodeToString(digest);
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("SHA-256 unavailable", e); // every JVM ships SHA-256
    }
  }

  /** The lockfile as text (deterministic ordering). */
  public String render() {
    StringBuilder sb = new StringBuilder();
    sb.append("# ").append(FILENAME).append(" — generated by elm-lang; do not edit by hand\n");
    sb.append("lockfileVersion ").append(FORMAT_VERSION).append("\n");
    packages.forEach(
        (pkg, e) -> sb.append(pkg).append(' ').append(e.version()).append(' ').append(e.integrity()).append('\n'));
    return sb.toString();
  }

  /** Parses a lockfile's text. Unknown/blank/comment lines are ignored; malformed entries are skipped. */
  public static Lockfile parse(String text) {
    SortedMap<String, Entry> entries = new TreeMap<>();
    for (String line : text.split("\n", -1)) {
      String trimmed = line.strip();
      if (trimmed.isEmpty() || trimmed.startsWith("#") || trimmed.startsWith("lockfileVersion")) {
        continue;
      }
      String[] parts = trimmed.split("\\s+");
      if (parts.length == 3 && parts[0].contains("/")) {
        entries.put(parts[0], new Entry(Version.parse(parts[1]), parts[2]));
      }
    }
    return new Lockfile(entries);
  }

  /**
   * Checks this lockfile against a registry: every locked package must still resolve to the same
   * integrity hash (the registry hasn't changed what that pinned version depends on). Returns a list
   * of human-readable problems — empty means the lockfile is intact.
   */
  public List<String> verify(Registry registry) {
    List<String> problems = new ArrayList<>();
    packages.forEach(
        (pkg, e) -> {
          String current = integrity(pkg, e.version(), registry);
          if (!current.equals(e.integrity())) {
            problems.add(
                "integrity mismatch for " + pkg + " " + e.version() + ": lock has " + e.integrity()
                    + " but registry now yields " + current);
          }
        });
    return problems;
  }

  /**
   * Checks that a set of resolved dependencies (from {@code elm.json}) matches this lockfile: every
   * dependency must be locked at the same version. Returns the problems found (empty = consistent).
   * Unlike {@link #verify}, this needs no registry — it's the reproducibility check a build can run
   * cheaply (the integrity-hash check is {@link #verify} / {@code elm verify}).
   */
  public List<String> checkVersions(Map<String, Version> deps) {
    List<String> problems = new ArrayList<>();
    deps.forEach(
        (pkg, version) -> {
          Entry locked = packages.get(pkg);
          if (locked == null) {
            problems.add(pkg + " " + version + " is in elm.json but not locked");
          } else if (!locked.version().equals(version)) {
            problems.add(
                pkg + " is " + version + " in elm.json but " + locked.version() + " in the lockfile");
          }
        });
    return problems;
  }

  /**
   * Checks that {@code elm.json}'s resolved dependencies match {@code elm.lock} and that every locked
   * package still verifies against the registry. Returns the problems found (empty = all good).
   */
  public static List<String> verifyProject(Path projectDir, Registry registry) throws IOException {
    Path lockPath = projectDir.resolve(FILENAME);
    Path elmJsonPath = projectDir.resolve("elm.json");
    if (!Files.exists(lockPath)) {
      return List.of("no " + FILENAME + " — run `elm install` to create one");
    }
    Lockfile lock = parse(Files.readString(lockPath, StandardCharsets.UTF_8));
    List<String> problems = new ArrayList<>(lock.verify(registry));
    if (Files.exists(elmJsonPath)) {
      ElmJson elm = ElmJson.parse(Files.readString(elmJsonPath, StandardCharsets.UTF_8));
      elm.all().forEach(
          (pkg, version) -> {
            Entry locked = lock.packages().get(pkg);
            if (locked == null) {
              problems.add(pkg + " " + version + " is in elm.json but not locked");
            } else if (!locked.version().equals(version)) {
              problems.add(pkg + " is " + version + " in elm.json but " + locked.version() + " in the lockfile");
            }
          });
    }
    return problems;
  }

  /** Writes the lockfile for a solution into {@code projectDir/elm.lock}. */
  public static void write(Path projectDir, Map<String, Version> solution, Registry registry)
      throws IOException {
    Files.writeString(projectDir.resolve(FILENAME), of(solution, registry).render(), StandardCharsets.UTF_8);
  }
}
