package pl.matsuo.elm.site;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * The compiler/Elm-generator split: SiteGenerator compiles the demo artifacts and a manifest, and
 * the Elm Gallery generator (run as a script) reads that manifest to produce ALL of the gallery's
 * HTML and CSS via the Site library.
 */
class GalleryTest {

  private static final Path EXAMPLES = Path.of("src/test/resources/examples");
  private static final Path PLAYGROUND = Path.of("src/test/resources/Playground.elm");

  @Test
  void siteGeneratorWritesAManifestOfArtifacts() throws IOException {
    Path out = Files.createTempDirectory("gallery-manifest-");
    SiteGenerator.generate(EXAMPLES, PLAYGROUND, out);
    String manifest = Files.readString(out.resolve("manifest.tsv"), StandardCharsets.UTF_8);
    // Each line: slug \t title \t category \t demoPath \t method.
    assertTrue(manifest.contains("hello\tHello\tHTML\tdemos/hello.html\t"), manifest);
    assertTrue(Files.exists(out.resolve("demos/hello.html")), "the demo artifact exists");
  }

  @Test
  void elmGeneratorProducesTheGalleryHtmlAndCss() throws IOException {
    Path out = Files.createTempDirectory("gallery-");
    int code = SiteGen.generateGallery(EXAMPLES, PLAYGROUND, out, null);
    assertTrue(code == 0, "the Elm gallery generator succeeded");

    // The index.html is now produced by the Elm generator (from the manifest), via the Site library.
    String index = Files.readString(out.resolve("index.html"), StandardCharsets.UTF_8);
    assertTrue(index.contains("Example gallery"), index.substring(0, Math.min(200, index.length())));
    assertTrue(index.contains("<h2>HTML</h2>"), "examples grouped by category");
    assertTrue(index.contains(">Hello</a>") && index.contains("href=\"demos/hello.html\""),
        "an example links its compiled demo artifact");
    assertTrue(index.contains("href=\"styles.css\""), "links the generated stylesheet");
    // Client-side search box, dark-mode toggle and the script that drives them.
    assertTrue(index.contains("id=\"search\""), "has a search box");
    assertTrue(index.contains("id=\"theme-toggle\""), "has a theme toggle");
    assertTrue(index.contains("data-name=\"hello\""), "cards carry a searchable name");
    assertTrue(index.contains("localStorage.getItem('theme')"), "theme is persisted client-side");

    // The CSS is generated by the Elm side too, including the dark theme.
    String css = Files.readString(out.resolve("styles.css"), StandardCharsets.UTF_8);
    assertTrue(css.contains(".card"), "gallery CSS generated");
    assertTrue(css.contains("prefers-color-scheme: dark"), "dark mode honours the OS preference");
    assertTrue(css.contains("[data-theme=dark]"), "dark mode also has an explicit toggle");

    // The demo artifacts (compiled by the Java side) are still present and live.
    assertTrue(
        Files.readString(out.resolve("demos/hello.html"), StandardCharsets.UTF_8).contains("$start"),
        "the demo is the JS-compiled bundle");
  }
}
